apiVersion: apps/v1
kind: Deployment
metadata:
  name: infosrv
spec:
  replicas: 1
  selector:
    matchLabels:
      name: infosrv
  template:
    metadata:
      labels:
        name: infosrv
    spec:
      containers:
        - name: infosrv
          image: ${REGISTRY}infosrv:latest
          ports:
            - containerPort: 9999
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-vol
